% Background Knowledge
% Generated by prolog_generator.py
% Project: Qualitative Analysis of Robotic Signal Components
% Author: Alisha Syed Karimulla
%
% Facts:
%   signal_shape(Run, Window, Sensor, Shape)
%   has_window(Run, Window)
%   scenario(Run, Scenario)
%   example_type(Run, Type)


% === Run: pill_bad_01 | Scenario: pillar_wall_bad | Type: negative ===
scenario(pill_bad_01, pillar_wall).
example_type(pill_bad_01, negative).
has_window(pill_bad_01, obstacle_detected).
has_window(pill_bad_01, obstacle_avoidance).
has_window(pill_bad_01, wall_reacquired).
has_window(pill_bad_01, approaching_wall).
has_window(pill_bad_01, wall_following).
signal_shape(pill_bad_01, obstacle_detected, lidar_left, is_increasing).
signal_shape(pill_bad_01, obstacle_detected, lidar_right, is_decreasing).
signal_shape(pill_bad_01, obstacle_detected, lidar_front, is_increasing).
signal_shape(pill_bad_01, obstacle_detected, lidar_front_right, is_decreasing).
signal_shape(pill_bad_01, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_bad_01, obstacle_detected, imu_accel_x, is_decreasing).
signal_shape(pill_bad_01, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_bad_01, obstacle_detected, odom_linear_x, is_zero).
signal_shape(pill_bad_01, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_bad_01, obstacle_avoidance, lidar_left, is_oscillating).
signal_shape(pill_bad_01, obstacle_avoidance, lidar_right, is_oscillating).
signal_shape(pill_bad_01, obstacle_avoidance, lidar_front, is_oscillating).
signal_shape(pill_bad_01, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_bad_01, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_bad_01, obstacle_avoidance, imu_accel_x, is_decreasing).
signal_shape(pill_bad_01, obstacle_avoidance, imu_accel_y, is_increasing).
signal_shape(pill_bad_01, obstacle_avoidance, odom_linear_x, is_zero).
signal_shape(pill_bad_01, obstacle_avoidance, odom_angular_z, is_oscillating).
signal_shape(pill_bad_01, wall_reacquired, lidar_left, is_constant).
signal_shape(pill_bad_01, wall_reacquired, lidar_right, is_oscillating).
signal_shape(pill_bad_01, wall_reacquired, lidar_front, is_increasing).
signal_shape(pill_bad_01, wall_reacquired, lidar_front_right, is_oscillating).
signal_shape(pill_bad_01, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_bad_01, wall_reacquired, imu_accel_x, is_oscillating).
signal_shape(pill_bad_01, wall_reacquired, imu_accel_y, is_oscillating).
signal_shape(pill_bad_01, wall_reacquired, odom_linear_x, is_zero).
signal_shape(pill_bad_01, wall_reacquired, odom_angular_z, is_zero).
signal_shape(pill_bad_01, approaching_wall, lidar_left, is_decreasing).
signal_shape(pill_bad_01, approaching_wall, lidar_right, is_oscillating).
signal_shape(pill_bad_01, approaching_wall, lidar_front, is_increasing).
signal_shape(pill_bad_01, approaching_wall, lidar_front_right, is_oscillating).
signal_shape(pill_bad_01, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pill_bad_01, approaching_wall, imu_accel_x, is_increasing).
signal_shape(pill_bad_01, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pill_bad_01, approaching_wall, odom_linear_x, is_zero).
signal_shape(pill_bad_01, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_bad_01, wall_following, lidar_left, is_constant).
signal_shape(pill_bad_01, wall_following, lidar_right, is_oscillating).
signal_shape(pill_bad_01, wall_following, lidar_front, is_oscillating).
signal_shape(pill_bad_01, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_bad_01, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_bad_01, wall_following, imu_accel_x, is_zero).
signal_shape(pill_bad_01, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_bad_01, wall_following, odom_linear_x, is_zero).
signal_shape(pill_bad_01, wall_following, odom_angular_z, is_zero).

% === Run: pill_bad_02 | Scenario: pillar_wall_bad | Type: negative ===
scenario(pill_bad_02, pillar_wall).
example_type(pill_bad_02, negative).
has_window(pill_bad_02, searching_wall).
has_window(pill_bad_02, approaching_wall).
has_window(pill_bad_02, obstacle_detected).
has_window(pill_bad_02, obstacle_avoidance).
signal_shape(pill_bad_02, searching_wall, lidar_left, is_oscillating).
signal_shape(pill_bad_02, searching_wall, lidar_right, is_oscillating).
signal_shape(pill_bad_02, searching_wall, lidar_front, is_oscillating).
signal_shape(pill_bad_02, searching_wall, lidar_front_right, is_decreasing).
signal_shape(pill_bad_02, searching_wall, imu_angular_z, is_oscillating).
signal_shape(pill_bad_02, searching_wall, imu_accel_x, is_increasing).
signal_shape(pill_bad_02, searching_wall, imu_accel_y, is_oscillating).
signal_shape(pill_bad_02, searching_wall, odom_linear_x, is_zero).
signal_shape(pill_bad_02, searching_wall, odom_angular_z, is_zero).
signal_shape(pill_bad_02, approaching_wall, lidar_left, is_oscillating).
signal_shape(pill_bad_02, approaching_wall, lidar_right, is_increasing).
signal_shape(pill_bad_02, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_bad_02, approaching_wall, lidar_front_right, is_decreasing).
signal_shape(pill_bad_02, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_bad_02, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pill_bad_02, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pill_bad_02, approaching_wall, odom_linear_x, is_zero).
signal_shape(pill_bad_02, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_bad_02, obstacle_detected, lidar_left, is_decreasing).
signal_shape(pill_bad_02, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_bad_02, obstacle_detected, lidar_front, is_constant).
signal_shape(pill_bad_02, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_bad_02, obstacle_detected, imu_angular_z, is_decreasing).
signal_shape(pill_bad_02, obstacle_detected, imu_accel_x, is_zero).
signal_shape(pill_bad_02, obstacle_detected, imu_accel_y, is_increasing).
signal_shape(pill_bad_02, obstacle_detected, odom_linear_x, is_zero).
signal_shape(pill_bad_02, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_bad_02, obstacle_avoidance, lidar_left, is_decreasing).
signal_shape(pill_bad_02, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_bad_02, obstacle_avoidance, lidar_front, is_increasing).
signal_shape(pill_bad_02, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_bad_02, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_bad_02, obstacle_avoidance, imu_accel_x, is_decreasing).
signal_shape(pill_bad_02, obstacle_avoidance, imu_accel_y, is_increasing).
signal_shape(pill_bad_02, obstacle_avoidance, odom_linear_x, is_zero).
signal_shape(pill_bad_02, obstacle_avoidance, odom_angular_z, is_zero).

% === Run: pill_bad_03 | Scenario: pillar_wall_bad | Type: negative ===
scenario(pill_bad_03, pillar_wall).
example_type(pill_bad_03, negative).
has_window(pill_bad_03, approaching_wall).
has_window(pill_bad_03, wall_following).
has_window(pill_bad_03, obstacle_detected).
has_window(pill_bad_03, obstacle_avoidance).
has_window(pill_bad_03, wall_reacquired).
has_window(pill_bad_03, wall_following_fail).
signal_shape(pill_bad_03, approaching_wall, lidar_left, is_oscillating).
signal_shape(pill_bad_03, approaching_wall, lidar_right, is_oscillating).
signal_shape(pill_bad_03, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_bad_03, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pill_bad_03, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_bad_03, approaching_wall, imu_accel_x, is_increasing).
signal_shape(pill_bad_03, approaching_wall, imu_accel_y, is_oscillating).
signal_shape(pill_bad_03, approaching_wall, odom_linear_x, is_zero).
signal_shape(pill_bad_03, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_bad_03, wall_following, lidar_left, is_constant).
signal_shape(pill_bad_03, wall_following, lidar_right, is_oscillating).
signal_shape(pill_bad_03, wall_following, lidar_front, is_oscillating).
signal_shape(pill_bad_03, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_bad_03, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_bad_03, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_bad_03, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_bad_03, wall_following, odom_linear_x, is_zero).
signal_shape(pill_bad_03, wall_following, odom_angular_z, is_zero).
signal_shape(pill_bad_03, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_bad_03, obstacle_detected, lidar_right, is_decreasing).
signal_shape(pill_bad_03, obstacle_detected, lidar_front, is_decreasing).
signal_shape(pill_bad_03, obstacle_detected, lidar_front_right, is_decreasing).
signal_shape(pill_bad_03, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_bad_03, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_bad_03, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_bad_03, obstacle_detected, odom_linear_x, is_zero).
signal_shape(pill_bad_03, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_bad_03, obstacle_avoidance, lidar_left, is_oscillating).
signal_shape(pill_bad_03, obstacle_avoidance, lidar_right, is_oscillating).
signal_shape(pill_bad_03, obstacle_avoidance, lidar_front, is_decreasing).
signal_shape(pill_bad_03, obstacle_avoidance, lidar_front_right, is_increasing).
signal_shape(pill_bad_03, obstacle_avoidance, imu_angular_z, is_oscillating).
signal_shape(pill_bad_03, obstacle_avoidance, imu_accel_x, is_increasing).
signal_shape(pill_bad_03, obstacle_avoidance, imu_accel_y, is_decreasing).
signal_shape(pill_bad_03, obstacle_avoidance, odom_linear_x, is_zero).
signal_shape(pill_bad_03, obstacle_avoidance, odom_angular_z, is_oscillating).
signal_shape(pill_bad_03, wall_reacquired, lidar_left, is_decreasing).
signal_shape(pill_bad_03, wall_reacquired, lidar_right, is_oscillating).
signal_shape(pill_bad_03, wall_reacquired, lidar_front, is_decreasing).
signal_shape(pill_bad_03, wall_reacquired, lidar_front_right, is_decreasing).
signal_shape(pill_bad_03, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_bad_03, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_bad_03, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_bad_03, wall_reacquired, odom_linear_x, is_zero).
signal_shape(pill_bad_03, wall_reacquired, odom_angular_z, is_zero).
signal_shape(pill_bad_03, wall_following_fail, lidar_left, is_constant).
signal_shape(pill_bad_03, wall_following_fail, lidar_right, is_constant).
signal_shape(pill_bad_03, wall_following_fail, lidar_front, is_constant).
signal_shape(pill_bad_03, wall_following_fail, lidar_front_right, is_constant).
signal_shape(pill_bad_03, wall_following_fail, imu_angular_z, is_decreasing).
signal_shape(pill_bad_03, wall_following_fail, imu_accel_x, is_increasing).
signal_shape(pill_bad_03, wall_following_fail, imu_accel_y, is_oscillating).
signal_shape(pill_bad_03, wall_following_fail, odom_linear_x, is_zero).
signal_shape(pill_bad_03, wall_following_fail, odom_angular_z, is_zero).

% === Run: pill_good_01 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_01, pillar_wall).
example_type(pill_good_01, positive).
has_window(pill_good_01, approaching_wall).
has_window(pill_good_01, wall_following).
has_window(pill_good_01, obstacle_detected).
has_window(pill_good_01, obstacle_avoidance).
has_window(pill_good_01, wall_reacquired).
signal_shape(pill_good_01, approaching_wall, lidar_left, is_decreasing).
signal_shape(pill_good_01, approaching_wall, lidar_right, is_oscillating).
signal_shape(pill_good_01, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_good_01, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pill_good_01, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pill_good_01, approaching_wall, imu_accel_x, is_increasing).
signal_shape(pill_good_01, approaching_wall, imu_accel_y, is_zero).
signal_shape(pill_good_01, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_01, wall_following, lidar_left, is_constant).
signal_shape(pill_good_01, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_01, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_01, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_01, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_good_01, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_01, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_01, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_01, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_01, obstacle_detected, lidar_right, is_decreasing).
signal_shape(pill_good_01, obstacle_detected, lidar_front, is_constant).
signal_shape(pill_good_01, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_01, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_good_01, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_01, obstacle_detected, imu_accel_y, is_increasing).
signal_shape(pill_good_01, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_01, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_01, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_good_01, obstacle_avoidance, lidar_front, is_constant).
signal_shape(pill_good_01, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_good_01, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_01, obstacle_avoidance, imu_accel_x, is_increasing).
signal_shape(pill_good_01, obstacle_avoidance, imu_accel_y, is_oscillating).
signal_shape(pill_good_01, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_01, wall_reacquired, lidar_left, is_constant).
signal_shape(pill_good_01, wall_reacquired, lidar_right, is_increasing).
signal_shape(pill_good_01, wall_reacquired, lidar_front, is_increasing).
signal_shape(pill_good_01, wall_reacquired, lidar_front_right, is_decreasing).
signal_shape(pill_good_01, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_01, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_01, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_01, wall_reacquired, odom_angular_z, is_zero).

% === Run: pill_good_02 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_02, pillar_wall).
example_type(pill_good_02, positive).
has_window(pill_good_02, approaching_wall).
has_window(pill_good_02, wall_following).
has_window(pill_good_02, obstacle_detected).
has_window(pill_good_02, obstacle_avoidance).
has_window(pill_good_02, wall_reacquired).
signal_shape(pill_good_02, approaching_wall, lidar_left, is_oscillating).
signal_shape(pill_good_02, approaching_wall, lidar_right, is_oscillating).
signal_shape(pill_good_02, approaching_wall, lidar_front, is_oscillating).
signal_shape(pill_good_02, approaching_wall, lidar_front_right, is_constant).
signal_shape(pill_good_02, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_good_02, approaching_wall, imu_accel_x, is_zero).
signal_shape(pill_good_02, approaching_wall, imu_accel_y, is_oscillating).
signal_shape(pill_good_02, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_02, wall_following, lidar_left, is_constant).
signal_shape(pill_good_02, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_02, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_02, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_02, wall_following, imu_angular_z, is_zero).
signal_shape(pill_good_02, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_02, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_02, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_02, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_02, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_good_02, obstacle_detected, lidar_front, is_constant).
signal_shape(pill_good_02, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_02, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_good_02, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_02, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_good_02, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_02, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_02, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_good_02, obstacle_avoidance, lidar_front, is_decreasing).
signal_shape(pill_good_02, obstacle_avoidance, lidar_front_right, is_constant).
signal_shape(pill_good_02, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_02, obstacle_avoidance, imu_accel_x, is_zero).
signal_shape(pill_good_02, obstacle_avoidance, imu_accel_y, is_decreasing).
signal_shape(pill_good_02, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_02, wall_reacquired, lidar_left, is_increasing).
signal_shape(pill_good_02, wall_reacquired, lidar_right, is_decreasing).
signal_shape(pill_good_02, wall_reacquired, lidar_front, is_decreasing).
signal_shape(pill_good_02, wall_reacquired, lidar_front_right, is_constant).
signal_shape(pill_good_02, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_02, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_02, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_02, wall_reacquired, odom_angular_z, is_zero).

% === Run: pill_good_03 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_03, pillar_wall).
example_type(pill_good_03, positive).
has_window(pill_good_03, approaching_wall).
has_window(pill_good_03, wall_following).
has_window(pill_good_03, obstacle_detected).
has_window(pill_good_03, obstacle_avoidance).
has_window(pill_good_03, wall_reacquired).
signal_shape(pill_good_03, approaching_wall, lidar_left, is_decreasing).
signal_shape(pill_good_03, approaching_wall, lidar_right, is_constant).
signal_shape(pill_good_03, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_good_03, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pill_good_03, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pill_good_03, approaching_wall, imu_accel_x, is_zero).
signal_shape(pill_good_03, approaching_wall, imu_accel_y, is_decreasing).
signal_shape(pill_good_03, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_03, wall_following, lidar_left, is_constant).
signal_shape(pill_good_03, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_03, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_03, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_03, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_good_03, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_03, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_03, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_03, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_03, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_good_03, obstacle_detected, lidar_front, is_oscillating).
signal_shape(pill_good_03, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_03, obstacle_detected, imu_angular_z, is_zero).
signal_shape(pill_good_03, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_03, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_good_03, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_03, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_03, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_good_03, obstacle_avoidance, lidar_front, is_increasing).
signal_shape(pill_good_03, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_good_03, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_03, obstacle_avoidance, imu_accel_x, is_decreasing).
signal_shape(pill_good_03, obstacle_avoidance, imu_accel_y, is_increasing).
signal_shape(pill_good_03, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_03, wall_reacquired, lidar_left, is_constant).
signal_shape(pill_good_03, wall_reacquired, lidar_right, is_increasing).
signal_shape(pill_good_03, wall_reacquired, lidar_front, is_increasing).
signal_shape(pill_good_03, wall_reacquired, lidar_front_right, is_constant).
signal_shape(pill_good_03, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_03, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_03, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_03, wall_reacquired, odom_angular_z, is_zero).

% === Run: pill_good_04 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_04, pillar_wall).
example_type(pill_good_04, positive).
has_window(pill_good_04, approaching_wall).
has_window(pill_good_04, wall_following).
has_window(pill_good_04, obstacle_detected).
has_window(pill_good_04, obstacle_avoidance).
has_window(pill_good_04, wall_reacquired).
signal_shape(pill_good_04, approaching_wall, lidar_left, is_decreasing).
signal_shape(pill_good_04, approaching_wall, lidar_right, is_increasing).
signal_shape(pill_good_04, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_good_04, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pill_good_04, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_good_04, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pill_good_04, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pill_good_04, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_04, wall_following, lidar_left, is_constant).
signal_shape(pill_good_04, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_04, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_04, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_04, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_good_04, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_04, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_04, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_04, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_04, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_good_04, obstacle_detected, lidar_front, is_constant).
signal_shape(pill_good_04, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_04, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_good_04, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_04, obstacle_detected, imu_accel_y, is_increasing).
signal_shape(pill_good_04, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_04, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_04, obstacle_avoidance, lidar_right, is_oscillating).
signal_shape(pill_good_04, obstacle_avoidance, lidar_front, is_increasing).
signal_shape(pill_good_04, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_good_04, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_04, obstacle_avoidance, imu_accel_x, is_increasing).
signal_shape(pill_good_04, obstacle_avoidance, imu_accel_y, is_increasing).
signal_shape(pill_good_04, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_04, wall_reacquired, lidar_left, is_constant).
signal_shape(pill_good_04, wall_reacquired, lidar_right, is_constant).
signal_shape(pill_good_04, wall_reacquired, lidar_front, is_decreasing).
signal_shape(pill_good_04, wall_reacquired, lidar_front_right, is_increasing).
signal_shape(pill_good_04, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_04, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_04, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_04, wall_reacquired, odom_angular_z, is_zero).

% === Run: pill_good_05 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_05, pillar_wall).
example_type(pill_good_05, positive).
has_window(pill_good_05, approaching_wall).
has_window(pill_good_05, wall_following).
has_window(pill_good_05, obstacle_detected).
has_window(pill_good_05, obstacle_avoidance).
has_window(pill_good_05, wall_reacquired).
signal_shape(pill_good_05, approaching_wall, lidar_left, is_oscillating).
signal_shape(pill_good_05, approaching_wall, lidar_right, is_oscillating).
signal_shape(pill_good_05, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_good_05, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pill_good_05, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_good_05, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pill_good_05, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pill_good_05, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_05, wall_following, lidar_left, is_constant).
signal_shape(pill_good_05, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_05, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_05, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_05, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_good_05, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_05, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_05, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_05, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_05, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_good_05, obstacle_detected, lidar_front, is_increasing).
signal_shape(pill_good_05, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_05, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_good_05, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_05, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_good_05, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_05, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_05, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_good_05, obstacle_avoidance, lidar_front, is_decreasing).
signal_shape(pill_good_05, obstacle_avoidance, lidar_front_right, is_constant).
signal_shape(pill_good_05, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_05, obstacle_avoidance, imu_accel_x, is_increasing).
signal_shape(pill_good_05, obstacle_avoidance, imu_accel_y, is_increasing).
signal_shape(pill_good_05, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_05, wall_reacquired, lidar_left, is_increasing).
signal_shape(pill_good_05, wall_reacquired, lidar_right, is_decreasing).
signal_shape(pill_good_05, wall_reacquired, lidar_front, is_increasing).
signal_shape(pill_good_05, wall_reacquired, lidar_front_right, is_decreasing).
signal_shape(pill_good_05, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_05, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_05, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_05, wall_reacquired, odom_angular_z, is_zero).

% === Run: pill_good_06 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_06, pillar_wall).
example_type(pill_good_06, positive).
has_window(pill_good_06, approaching_wall).
has_window(pill_good_06, wall_following).
has_window(pill_good_06, obstacle_detected).
has_window(pill_good_06, obstacle_avoidance).
has_window(pill_good_06, wall_reacquired).
signal_shape(pill_good_06, approaching_wall, lidar_left, is_decreasing).
signal_shape(pill_good_06, approaching_wall, lidar_right, is_increasing).
signal_shape(pill_good_06, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_good_06, approaching_wall, lidar_front_right, is_oscillating).
signal_shape(pill_good_06, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_good_06, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pill_good_06, approaching_wall, imu_accel_y, is_oscillating).
signal_shape(pill_good_06, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_06, wall_following, lidar_left, is_constant).
signal_shape(pill_good_06, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_06, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_06, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_06, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_good_06, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_06, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_06, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_06, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_06, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_good_06, obstacle_detected, lidar_front, is_constant).
signal_shape(pill_good_06, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_06, obstacle_detected, imu_angular_z, is_zero).
signal_shape(pill_good_06, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_06, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_good_06, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_06, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_06, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_good_06, obstacle_avoidance, lidar_front, is_increasing).
signal_shape(pill_good_06, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_good_06, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_06, obstacle_avoidance, imu_accel_x, is_increasing).
signal_shape(pill_good_06, obstacle_avoidance, imu_accel_y, is_zero).
signal_shape(pill_good_06, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_06, wall_reacquired, lidar_left, is_constant).
signal_shape(pill_good_06, wall_reacquired, lidar_right, is_increasing).
signal_shape(pill_good_06, wall_reacquired, lidar_front, is_constant).
signal_shape(pill_good_06, wall_reacquired, lidar_front_right, is_constant).
signal_shape(pill_good_06, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_06, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_06, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_06, wall_reacquired, odom_angular_z, is_zero).

% === Run: pill_good_07 | Scenario: pillar_wall_good | Type: positive ===
scenario(pill_good_07, pillar_wall).
example_type(pill_good_07, positive).
has_window(pill_good_07, approaching_wall).
has_window(pill_good_07, wall_following).
has_window(pill_good_07, obstacle_detected).
has_window(pill_good_07, obstacle_avoidance).
has_window(pill_good_07, wall_reacquired).
signal_shape(pill_good_07, approaching_wall, lidar_left, is_decreasing).
signal_shape(pill_good_07, approaching_wall, lidar_right, is_oscillating).
signal_shape(pill_good_07, approaching_wall, lidar_front, is_decreasing).
signal_shape(pill_good_07, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pill_good_07, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pill_good_07, approaching_wall, imu_accel_x, is_zero).
signal_shape(pill_good_07, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pill_good_07, approaching_wall, odom_angular_z, is_zero).
signal_shape(pill_good_07, wall_following, lidar_left, is_constant).
signal_shape(pill_good_07, wall_following, lidar_right, is_oscillating).
signal_shape(pill_good_07, wall_following, lidar_front, is_oscillating).
signal_shape(pill_good_07, wall_following, lidar_front_right, is_oscillating).
signal_shape(pill_good_07, wall_following, imu_angular_z, is_oscillating).
signal_shape(pill_good_07, wall_following, imu_accel_x, is_oscillating).
signal_shape(pill_good_07, wall_following, imu_accel_y, is_oscillating).
signal_shape(pill_good_07, wall_following, odom_angular_z, is_zero).
signal_shape(pill_good_07, obstacle_detected, lidar_left, is_constant).
signal_shape(pill_good_07, obstacle_detected, lidar_right, is_constant).
signal_shape(pill_good_07, obstacle_detected, lidar_front, is_constant).
signal_shape(pill_good_07, obstacle_detected, lidar_front_right, is_constant).
signal_shape(pill_good_07, obstacle_detected, imu_angular_z, is_increasing).
signal_shape(pill_good_07, obstacle_detected, imu_accel_x, is_increasing).
signal_shape(pill_good_07, obstacle_detected, imu_accel_y, is_decreasing).
signal_shape(pill_good_07, obstacle_detected, odom_angular_z, is_zero).
signal_shape(pill_good_07, obstacle_avoidance, lidar_left, is_increasing).
signal_shape(pill_good_07, obstacle_avoidance, lidar_right, is_decreasing).
signal_shape(pill_good_07, obstacle_avoidance, lidar_front, is_increasing).
signal_shape(pill_good_07, obstacle_avoidance, lidar_front_right, is_decreasing).
signal_shape(pill_good_07, obstacle_avoidance, imu_angular_z, is_increasing).
signal_shape(pill_good_07, obstacle_avoidance, imu_accel_x, is_oscillating).
signal_shape(pill_good_07, obstacle_avoidance, imu_accel_y, is_increasing).
signal_shape(pill_good_07, obstacle_avoidance, odom_angular_z, is_decreasing).
signal_shape(pill_good_07, wall_reacquired, lidar_left, is_constant).
signal_shape(pill_good_07, wall_reacquired, lidar_right, is_increasing).
signal_shape(pill_good_07, wall_reacquired, lidar_front, is_constant).
signal_shape(pill_good_07, wall_reacquired, lidar_front_right, is_constant).
signal_shape(pill_good_07, wall_reacquired, imu_angular_z, is_increasing).
signal_shape(pill_good_07, wall_reacquired, imu_accel_x, is_increasing).
signal_shape(pill_good_07, wall_reacquired, imu_accel_y, is_decreasing).
signal_shape(pill_good_07, wall_reacquired, odom_angular_z, is_zero).

% === Run: pw_bad_01 | Scenario: plain_wall_bad | Type: negative ===
scenario(pw_bad_01, plain_wall).
example_type(pw_bad_01, negative).
has_window(pw_bad_01, approaching_wall).
has_window(pw_bad_01, searching_wall).
has_window(pw_bad_01, wall_following).
signal_shape(pw_bad_01, approaching_wall, lidar_left, is_oscillating).
signal_shape(pw_bad_01, approaching_wall, lidar_right, is_oscillating).
signal_shape(pw_bad_01, approaching_wall, lidar_front, is_oscillating).
signal_shape(pw_bad_01, approaching_wall, lidar_front_right, is_oscillating).
signal_shape(pw_bad_01, approaching_wall, imu_angular_z, is_oscillating).
signal_shape(pw_bad_01, approaching_wall, imu_accel_x, is_zero).
signal_shape(pw_bad_01, approaching_wall, imu_accel_y, is_oscillating).
signal_shape(pw_bad_01, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_bad_01, approaching_wall, odom_angular_z, is_oscillating).
signal_shape(pw_bad_01, searching_wall, lidar_left, is_oscillating).
signal_shape(pw_bad_01, searching_wall, lidar_right, is_oscillating).
signal_shape(pw_bad_01, searching_wall, lidar_front, is_oscillating).
signal_shape(pw_bad_01, searching_wall, lidar_front_right, is_oscillating).
signal_shape(pw_bad_01, searching_wall, imu_angular_z, is_oscillating).
signal_shape(pw_bad_01, searching_wall, imu_accel_x, is_oscillating).
signal_shape(pw_bad_01, searching_wall, imu_accel_y, is_oscillating).
signal_shape(pw_bad_01, searching_wall, odom_linear_x, is_zero).
signal_shape(pw_bad_01, searching_wall, odom_angular_z, is_oscillating).
signal_shape(pw_bad_01, wall_following, lidar_left, is_constant).
signal_shape(pw_bad_01, wall_following, lidar_right, is_oscillating).
signal_shape(pw_bad_01, wall_following, lidar_front, is_oscillating).
signal_shape(pw_bad_01, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_bad_01, wall_following, imu_angular_z, is_zero).
signal_shape(pw_bad_01, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_bad_01, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_bad_01, wall_following, odom_linear_x, is_zero).
signal_shape(pw_bad_01, wall_following, odom_angular_z, is_zero).

% === Run: pw_bad_02 | Scenario: plain_wall_bad | Type: negative ===
scenario(pw_bad_02, plain_wall).
example_type(pw_bad_02, negative).
has_window(pw_bad_02, wall_following).
signal_shape(pw_bad_02, wall_following, imu_angular_z, is_decreasing).
signal_shape(pw_bad_02, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_bad_02, wall_following, imu_accel_y, is_oscillating).

% === Run: pw_bad_03 | Scenario: plain_wall_bad | Type: negative ===
scenario(pw_bad_03, plain_wall).
example_type(pw_bad_03, negative).
has_window(pw_bad_03, wall_following_fail).
has_window(pw_bad_03, wall_following).
signal_shape(pw_bad_03, wall_following_fail, lidar_left, is_oscillating).
signal_shape(pw_bad_03, wall_following_fail, lidar_right, is_oscillating).
signal_shape(pw_bad_03, wall_following_fail, lidar_front, is_decreasing).
signal_shape(pw_bad_03, wall_following_fail, lidar_front_right, is_decreasing).
signal_shape(pw_bad_03, wall_following_fail, imu_angular_z, is_decreasing).
signal_shape(pw_bad_03, wall_following_fail, imu_accel_x, is_increasing).
signal_shape(pw_bad_03, wall_following_fail, imu_accel_y, is_oscillating).
signal_shape(pw_bad_03, wall_following_fail, odom_linear_x, is_zero).
signal_shape(pw_bad_03, wall_following, lidar_left, is_constant).
signal_shape(pw_bad_03, wall_following, lidar_right, is_oscillating).
signal_shape(pw_bad_03, wall_following, lidar_front, is_oscillating).
signal_shape(pw_bad_03, wall_following, lidar_front_right, is_decreasing).
signal_shape(pw_bad_03, wall_following, imu_angular_z, is_oscillating).
signal_shape(pw_bad_03, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_bad_03, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_bad_03, wall_following, odom_linear_x, is_zero).

% === Run: pw_bad_04 | Scenario: plain_wall_bad | Type: negative ===
scenario(pw_bad_04, plain_wall).
example_type(pw_bad_04, negative).
has_window(pw_bad_04, wall_following_fail).
has_window(pw_bad_04, wall_following).
has_window(pw_bad_04, approaching_wall).
signal_shape(pw_bad_04, wall_following_fail, lidar_left, is_oscillating).
signal_shape(pw_bad_04, wall_following_fail, lidar_right, is_oscillating).
signal_shape(pw_bad_04, wall_following_fail, lidar_front, is_increasing).
signal_shape(pw_bad_04, wall_following_fail, lidar_front_right, is_decreasing).
signal_shape(pw_bad_04, wall_following_fail, imu_angular_z, is_oscillating).
signal_shape(pw_bad_04, wall_following_fail, imu_accel_x, is_decreasing).
signal_shape(pw_bad_04, wall_following_fail, imu_accel_y, is_oscillating).
signal_shape(pw_bad_04, wall_following_fail, odom_linear_x, is_zero).
signal_shape(pw_bad_04, wall_following, lidar_left, is_constant).
signal_shape(pw_bad_04, wall_following, lidar_right, is_oscillating).
signal_shape(pw_bad_04, wall_following, lidar_front, is_oscillating).
signal_shape(pw_bad_04, wall_following, lidar_front_right, is_decreasing).
signal_shape(pw_bad_04, wall_following, imu_angular_z, is_oscillating).
signal_shape(pw_bad_04, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_bad_04, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_bad_04, wall_following, odom_linear_x, is_zero).
signal_shape(pw_bad_04, approaching_wall, lidar_left, is_constant).
signal_shape(pw_bad_04, approaching_wall, lidar_right, is_constant).
signal_shape(pw_bad_04, approaching_wall, lidar_front, is_decreasing).
signal_shape(pw_bad_04, approaching_wall, lidar_front_right, is_constant).
signal_shape(pw_bad_04, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_bad_04, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_bad_04, approaching_wall, imu_accel_y, is_decreasing).
signal_shape(pw_bad_04, approaching_wall, odom_linear_x, is_zero).

% === Run: pw_bad_05 | Scenario: plain_wall_bad | Type: negative ===
scenario(pw_bad_05, plain_wall).
example_type(pw_bad_05, negative).
has_window(pw_bad_05, wall_following_fail).
has_window(pw_bad_05, wall_following).
has_window(pw_bad_05, approaching_wall).
signal_shape(pw_bad_05, wall_following_fail, lidar_left, is_constant).
signal_shape(pw_bad_05, wall_following_fail, lidar_right, is_oscillating).
signal_shape(pw_bad_05, wall_following_fail, lidar_front, is_increasing).
signal_shape(pw_bad_05, wall_following_fail, lidar_front_right, is_decreasing).
signal_shape(pw_bad_05, wall_following_fail, imu_angular_z, is_decreasing).
signal_shape(pw_bad_05, wall_following_fail, imu_accel_x, is_oscillating).
signal_shape(pw_bad_05, wall_following_fail, imu_accel_y, is_oscillating).
signal_shape(pw_bad_05, wall_following_fail, odom_linear_x, is_zero).
signal_shape(pw_bad_05, wall_following_fail, odom_angular_z, is_zero).
signal_shape(pw_bad_05, wall_following, lidar_left, is_constant).
signal_shape(pw_bad_05, wall_following, lidar_right, is_oscillating).
signal_shape(pw_bad_05, wall_following, lidar_front, is_oscillating).
signal_shape(pw_bad_05, wall_following, lidar_front_right, is_decreasing).
signal_shape(pw_bad_05, wall_following, imu_angular_z, is_oscillating).
signal_shape(pw_bad_05, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_bad_05, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_bad_05, wall_following, odom_linear_x, is_zero).
signal_shape(pw_bad_05, wall_following, odom_angular_z, is_zero).
signal_shape(pw_bad_05, approaching_wall, lidar_left, is_constant).
signal_shape(pw_bad_05, approaching_wall, lidar_right, is_oscillating).
signal_shape(pw_bad_05, approaching_wall, lidar_front, is_increasing).
signal_shape(pw_bad_05, approaching_wall, lidar_front_right, is_decreasing).
signal_shape(pw_bad_05, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pw_bad_05, approaching_wall, imu_accel_x, is_increasing).
signal_shape(pw_bad_05, approaching_wall, imu_accel_y, is_decreasing).
signal_shape(pw_bad_05, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_bad_05, approaching_wall, odom_angular_z, is_zero).

% === Run: pw_good_01 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_01, plain_wall).
example_type(pw_good_01, positive).
has_window(pw_good_01, approaching_wall).
has_window(pw_good_01, wall_following).
signal_shape(pw_good_01, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_01, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_01, approaching_wall, lidar_front, is_increasing).
signal_shape(pw_good_01, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_01, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_good_01, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_good_01, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_01, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_01, wall_following, lidar_left, is_constant).
signal_shape(pw_good_01, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_01, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_01, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_01, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_01, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_01, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_01, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_02 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_02, plain_wall).
example_type(pw_good_02, positive).
has_window(pw_good_02, approaching_wall).
has_window(pw_good_02, wall_following).
signal_shape(pw_good_02, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_02, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_02, approaching_wall, lidar_front, is_decreasing).
signal_shape(pw_good_02, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_02, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_good_02, approaching_wall, imu_accel_x, is_zero).
signal_shape(pw_good_02, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_02, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_02, wall_following, lidar_left, is_constant).
signal_shape(pw_good_02, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_02, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_02, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_02, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_02, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_02, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_02, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_03 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_03, plain_wall).
example_type(pw_good_03, positive).
has_window(pw_good_03, approaching_wall).
has_window(pw_good_03, wall_following).
signal_shape(pw_good_03, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_03, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_03, approaching_wall, lidar_front, is_decreasing).
signal_shape(pw_good_03, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_03, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pw_good_03, approaching_wall, imu_accel_x, is_zero).
signal_shape(pw_good_03, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_03, wall_following, lidar_left, is_constant).
signal_shape(pw_good_03, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_03, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_03, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_03, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_03, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_03, wall_following, imu_accel_y, is_oscillating).

% === Run: pw_good_04 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_04, plain_wall).
example_type(pw_good_04, positive).
has_window(pw_good_04, approaching_wall).
has_window(pw_good_04, wall_following).
signal_shape(pw_good_04, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_04, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_04, approaching_wall, lidar_front, is_decreasing).
signal_shape(pw_good_04, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_04, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pw_good_04, approaching_wall, imu_accel_x, is_increasing).
signal_shape(pw_good_04, approaching_wall, imu_accel_y, is_decreasing).
signal_shape(pw_good_04, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_04, wall_following, lidar_left, is_constant).
signal_shape(pw_good_04, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_04, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_04, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_04, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_04, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_04, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_04, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_05 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_05, plain_wall).
example_type(pw_good_05, positive).
has_window(pw_good_05, approaching_wall).
has_window(pw_good_05, wall_following).
signal_shape(pw_good_05, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_05, approaching_wall, lidar_right, is_oscillating).
signal_shape(pw_good_05, approaching_wall, lidar_front, is_oscillating).
signal_shape(pw_good_05, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_05, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_good_05, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_good_05, approaching_wall, imu_accel_y, is_oscillating).
signal_shape(pw_good_05, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_05, wall_following, lidar_left, is_constant).
signal_shape(pw_good_05, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_05, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_05, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_05, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_05, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_05, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_05, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_06 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_06, plain_wall).
example_type(pw_good_06, positive).
has_window(pw_good_06, approaching_wall).
has_window(pw_good_06, wall_following).
signal_shape(pw_good_06, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_06, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_06, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_06, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pw_good_06, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_good_06, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_06, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_06, wall_following, lidar_left, is_constant).
signal_shape(pw_good_06, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_06, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_06, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_06, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_06, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_06, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_07 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_07, plain_wall).
example_type(pw_good_07, positive).
has_window(pw_good_07, approaching_wall).
has_window(pw_good_07, wall_following).
signal_shape(pw_good_07, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_07, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_07, approaching_wall, lidar_front, is_oscillating).
signal_shape(pw_good_07, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_07, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_good_07, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_good_07, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_07, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_07, wall_following, lidar_left, is_constant).
signal_shape(pw_good_07, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_07, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_07, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_07, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_07, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_07, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_07, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_08 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_08, plain_wall).
example_type(pw_good_08, positive).
has_window(pw_good_08, approaching_wall).
has_window(pw_good_08, wall_following).
signal_shape(pw_good_08, approaching_wall, lidar_left, is_oscillating).
signal_shape(pw_good_08, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_08, approaching_wall, lidar_front, is_increasing).
signal_shape(pw_good_08, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_08, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pw_good_08, approaching_wall, imu_accel_x, is_zero).
signal_shape(pw_good_08, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_08, wall_following, lidar_left, is_constant).
signal_shape(pw_good_08, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_08, wall_following, lidar_front, is_constant).
signal_shape(pw_good_08, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_08, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_08, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_08, wall_following, imu_accel_y, is_oscillating).

% === Run: pw_good_09 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_09, plain_wall).
example_type(pw_good_09, positive).
has_window(pw_good_09, approaching_wall).
has_window(pw_good_09, wall_following).
signal_shape(pw_good_09, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_09, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_09, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_09, approaching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_good_09, approaching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_good_09, approaching_wall, imu_accel_y, is_increasing).
signal_shape(pw_good_09, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_09, wall_following, lidar_left, is_constant).
signal_shape(pw_good_09, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_09, wall_following, lidar_front_right, is_oscillating).
signal_shape(pw_good_09, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_09, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_09, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_09, wall_following, odom_linear_x, is_zero).

% === Run: pw_good_10 | Scenario: plain_wall_good | Type: positive ===
scenario(pw_good_10, plain_wall).
example_type(pw_good_10, positive).
has_window(pw_good_10, searching_wall).
has_window(pw_good_10, approaching_wall).
has_window(pw_good_10, wall_following).
signal_shape(pw_good_10, searching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_10, searching_wall, lidar_right, is_increasing).
signal_shape(pw_good_10, searching_wall, lidar_front, is_increasing).
signal_shape(pw_good_10, searching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_10, searching_wall, imu_angular_z, is_decreasing).
signal_shape(pw_good_10, searching_wall, imu_accel_x, is_decreasing).
signal_shape(pw_good_10, searching_wall, imu_accel_y, is_decreasing).
signal_shape(pw_good_10, searching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_10, approaching_wall, lidar_left, is_decreasing).
signal_shape(pw_good_10, approaching_wall, lidar_right, is_increasing).
signal_shape(pw_good_10, approaching_wall, lidar_front, is_oscillating).
signal_shape(pw_good_10, approaching_wall, lidar_front_right, is_increasing).
signal_shape(pw_good_10, approaching_wall, imu_angular_z, is_increasing).
signal_shape(pw_good_10, approaching_wall, imu_accel_x, is_increasing).
signal_shape(pw_good_10, approaching_wall, imu_accel_y, is_oscillating).
signal_shape(pw_good_10, approaching_wall, odom_linear_x, is_zero).
signal_shape(pw_good_10, wall_following, lidar_left, is_constant).
signal_shape(pw_good_10, wall_following, lidar_right, is_oscillating).
signal_shape(pw_good_10, wall_following, lidar_front, is_oscillating).
signal_shape(pw_good_10, wall_following, lidar_front_right, is_decreasing).
signal_shape(pw_good_10, wall_following, imu_angular_z, is_zero).
signal_shape(pw_good_10, wall_following, imu_accel_x, is_oscillating).
signal_shape(pw_good_10, wall_following, imu_accel_y, is_oscillating).
signal_shape(pw_good_10, wall_following, odom_linear_x, is_zero).
