#!/usr/bin/env python3
"""
Prolog Generator for Robile Wall Following ILP
===============================================
This script:
1. Reads QTA JSON results (from qta_visualizer.py)
2. Converts QTA shapes to Prolog facts
3. Creates three files for Popper ILP:
   - bk.pl          (background knowledge - all facts)
   - positive.pl    (good examples)
   - negative.pl    (bad examples)

Author: Alisha Syed Karimulla
Project: Qualitative Analysis of Robotic Signal
         Components using ILP
"""

import json
import os


# ── CONFIGURATION ─────────────────────────────────────────────

# Input: QTA results folder
QTA_DIR    = os.path.expanduser(
    '~/rnd_ws/qta_results')

# Output: Popper ILP files folder
OUTPUT_DIR = os.path.expanduser(
    '~/rnd_ws/ilp_files')

# Sensors to include in Prolog facts
# (based on event detection findings)
SENSORS_TO_USE = [
    'lidar_left',
    'lidar_right',
    'lidar_front',
    'lidar_front_right',
    'imu_angular_z',
    'imu_accel_x',
    'imu_accel_y',
    'odom_linear_x',
    'odom_angular_z',
]

# Action windows to include
WINDOWS_TO_USE = [
    'approaching_wall',
    'wall_following',
    'wall_following_fail',
    'obstacle_detected',
    'obstacle_avoidance',
    'wall_reacquired',
    'searching_wall',
]
# ──────────────────────────────────────────────────────────────


def load_qta_results():
    """
    Loads all QTA JSON files from qta_results folder.
    Returns list of QTA result dictionaries.
    """
    all_results = []
    json_files  = sorted([
        f for f in os.listdir(QTA_DIR)
        if f.endswith('_qta.json')])

    print(f'Found {len(json_files)} QTA result files')

    for filename in json_files:
        filepath = os.path.join(QTA_DIR, filename)
        with open(filepath, 'r') as f:
            result = json.load(f)
            all_results.append(result)
            print(f'  Loaded: {filename}')

    return all_results


def generate_signal_shape_facts(result):
    """
    Converts one QTA result into Prolog facts.

    Example output:
    signal_shape(pw_good_01, wall_following,
                 lidar_left, is_constant).
    """
    facts   = []
    run_id  = result['run_id']
    windows = result.get('windows', {})

    for window_name, sensors in windows.items():

        # Skip windows we don't care about
        if window_name not in WINDOWS_TO_USE:
            continue

        for sensor, info in sensors.items():

            # Skip sensors we don't use
            if sensor not in SENSORS_TO_USE:
                continue

            shape = info['shape']

            # Create Prolog fact
            fact = (
                f'signal_shape('
                f'{run_id}, '
                f'{window_name}, '
                f'{sensor}, '
                f'{shape}).'
            )
            facts.append(fact)

    return facts


def generate_has_window_facts(result):
    """
    Creates facts about which action windows
    exist in each run.

    Example output:
    has_window(pw_good_01, wall_following).
    has_window(pw_good_01, approaching_wall).
    """
    facts   = []
    run_id  = result['run_id']
    windows = result.get('windows', {})

    for window_name in windows.keys():
        if window_name in WINDOWS_TO_USE:
            fact = (
                f'has_window('
                f'{run_id}, '
                f'{window_name}).'
            )
            facts.append(fact)

    return facts


def generate_scenario_facts(result):
    """
    Creates facts about which scenario each run is.

    Example output:
    scenario(pw_good_01, plain_wall).
    scenario(pill_good_01, pillar_wall).
    """
    run_id   = result['run_id']
    scenario = result.get('scenario', 'unknown')

    # Simplify scenario name
    if 'plain' in scenario:
        scenario_name = 'plain_wall'
    elif 'pillar' in scenario:
        scenario_name = 'pillar_wall'
    else:
        scenario_name = 'unknown'

    fact = (
        f'scenario('
        f'{run_id}, '
        f'{scenario_name}).'
    )
    return [fact]


def generate_example_type_facts(result):
    """
    Creates facts about positive/negative type.

    Example output:
    example_type(pw_good_01, positive).
    example_type(pw_bad_01, negative).
    """
    run_id       = result['run_id']
    example_type = result.get(
        'example_type', 'unknown')

    fact = (
        f'example_type('
        f'{run_id}, '
        f'{example_type}).'
    )
    return [fact]


def write_background_knowledge(all_results):
    """
    Writes bk.pl — background knowledge file.
    Contains ALL Prolog facts about all runs.
    This is what Popper reads to learn rules!
    """
    bk_path = os.path.join(OUTPUT_DIR, 'bk.pl')

    with open(bk_path, 'w') as f:

        # Write header
        f.write('% Background Knowledge\n')
        f.write('% Generated by prolog_generator.py\n')
        f.write('% Project: Qualitative Analysis ')
        f.write('of Robotic Signal Components\n')
        f.write('% Author: Alisha Syed Karimulla\n')
        f.write('%\n')
        f.write('% Facts:\n')
        f.write('%   signal_shape(Run, Window, ')
        f.write('Sensor, Shape)\n')
        f.write('%   has_window(Run, Window)\n')
        f.write('%   scenario(Run, Scenario)\n')
        f.write('%   example_type(Run, Type)\n')
        f.write('\n')

        total_facts = 0

        for result in all_results:
            run_id = result['run_id']
            f.write(f'\n% === Run: {run_id} ')
            f.write(f'| Scenario: ')
            f.write(f'{result.get("scenario")} ')
            f.write(f'| Type: ')
            f.write(f'{result.get("example_type")} ')
            f.write('===\n')

            # Write scenario facts
            for fact in generate_scenario_facts(
                    result):
                f.write(fact + '\n')
                total_facts += 1

            # Write example type facts
            for fact in generate_example_type_facts(
                    result):
                f.write(fact + '\n')
                total_facts += 1

            # Write has_window facts
            for fact in generate_has_window_facts(
                    result):
                f.write(fact + '\n')
                total_facts += 1

            # Write signal_shape facts
            for fact in generate_signal_shape_facts(
                    result):
                f.write(fact + '\n')
                total_facts += 1

    print(f'\n✅ bk.pl saved: {total_facts} facts')
    return bk_path


def write_positive_examples(all_results):
    """
    Writes positive.pl — positive examples.
    Contains run IDs of GOOD robot behavior.
    """
    pos_path = os.path.join(
        OUTPUT_DIR, 'positive.pl')

    positive_runs = [
        r for r in all_results
        if r.get('example_type') == 'positive']

    with open(pos_path, 'w') as f:
        f.write('% Positive Examples\n')
        f.write('% Good robot behavior runs\n\n')

        for result in positive_runs:
            run_id   = result['run_id']
            scenario = result.get('scenario', '')

            f.write(f'% {scenario}\n')
            f.write(
                f'wall_following({run_id}).\n')

    print(f'✅ positive.pl saved: '
          f'{len(positive_runs)} examples')
    return pos_path


def write_negative_examples(all_results):
    """
    Writes negative.pl — negative examples.
    Contains run IDs of BAD robot behavior.
    """
    neg_path = os.path.join(
        OUTPUT_DIR, 'negative.pl')

    negative_runs = [
        r for r in all_results
        if r.get('example_type') == 'negative']

    with open(neg_path, 'w') as f:
        f.write('% Negative Examples\n')
        f.write('% Bad robot behavior runs\n\n')

        for result in negative_runs:
            run_id   = result['run_id']
            scenario = result.get('scenario', '')

            f.write(f'% {scenario}\n')
            f.write(
                f'wall_following({run_id}).\n')

    print(f'✅ negative.pl saved: '
          f'{len(negative_runs)} examples')
    return neg_path


def write_bias_file():
    """
    Writes bias.pl — tells Popper what kind
    of rules to look for.

    This is like giving Popper a template
    for what rules should look like!
    """
    bias_path = os.path.join(
        OUTPUT_DIR, 'bias.pl')

    with open(bias_path, 'w') as f:
        f.write('% Bias File for Popper ILP\n')
        f.write('% Defines search space ')
        f.write('for rule learning\n\n')

        # Head declaration
        f.write('% Target predicate to learn\n')
        f.write('head_pred(wall_following, 1).\n\n')

        # Body declarations
        f.write('% Predicates allowed in rule body\n')
        f.write('body_pred(signal_shape, 4).\n')
        f.write('body_pred(has_window, 2).\n')
        f.write('body_pred(scenario, 2).\n\n')

        # Type declarations
        f.write('% Type declarations\n')
        f.write('type(wall_following, '
                '(run,)).\n')
        f.write('type(signal_shape, '
                '(run, window, sensor, shape)).\n')
        f.write('type(has_window, '
                '(run, window)).\n')
        f.write('type(scenario, '
                '(run, scenario)).\n\n')

        # Direction declarations
        f.write('% Direction declarations\n')
        f.write('direction(wall_following, '
                '(in,)).\n')
        f.write('direction(signal_shape, '
                '(in, in, in, out)).\n')
        f.write('direction(has_window, '
                '(in, in)).\n')
        f.write('direction(scenario, '
                '(in, in)).\n\n')

        # Search limits
        f.write('% Search limits\n')
        f.write('max_clauses(5).\n')
        f.write('max_body(4).\n')
        f.write('max_vars(6).\n')

    print(f'✅ bias.pl saved!')
    return bias_path


def print_summary(all_results):
    """
    Prints a summary of what was generated.
    """
    positive = [r for r in all_results
                if r.get('example_type') == 'positive']
    negative = [r for r in all_results
                if r.get('example_type') == 'negative']

    print('\n' + '='*60)
    print('PROLOG GENERATION SUMMARY')
    print('='*60)
    print(f'Total runs processed: {len(all_results)}')
    print(f'Positive examples:    {len(positive)}')
    print(f'Negative examples:    {len(negative)}')

    print('\nPositive runs:')
    for r in positive:
        print(f'  ✅ {r["run_id"]:20s} '
              f'({r.get("scenario")})')

    print('\nNegative runs:')
    for r in negative:
        print(f'  ❌ {r["run_id"]:20s} '
              f'({r.get("scenario")})')

    print('\nFiles created:')
    print(f'  📄 bk.pl       ← background knowledge')
    print(f'  📄 positive.pl ← good examples')
    print(f'  📄 negative.pl ← bad examples')
    print(f'  📄 bias.pl     ← Popper search space')
    print(f'\nAll saved to: {OUTPUT_DIR}')
    print('\nNext step: Install and run Popper ILP!')
    print('='*60)


# ── MAIN ──────────────────────────────────────────────────────
if __name__ == '__main__':

    print('='*60)
    print('PROLOG GENERATOR')
    print('Robile Wall Following ILP')
    print('='*60)

    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Load QTA results
    print('\nLoading QTA results...')
    all_results = load_qta_results()

    # Generate Prolog files
    print('\nGenerating Prolog files...')
    write_background_knowledge(all_results)
    write_positive_examples(all_results)
    write_negative_examples(all_results)
    write_bias_file()

    # Print summary
    print_summary(all_results)